import 'package:flutter/material.dart';
import '../models/quality_check.dart';

class QualityCheckCard extends StatelessWidget {
  final List<QualityCheckResult> results;

  const QualityCheckCard({super.key, required this.results});

  @override
  Widget build(BuildContext context) {
    // Count results by status
    final passing = results.where((r) => r.status == CheckStatus.ok).length;
    final warnings = results.where((r) => r.status == CheckStatus.warning).length;
    final overallStatus = warnings > 0 || passing < results.length ? 'REVIEW' : 'PASSING';
    final statusColor = warnings > 0 || passing < results.length ? Colors.orange : Colors.green;
    
    return Container(
      padding: const EdgeInsets.all(24.0),
      child: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Quality Control Hub',
              style: TextStyle(
                color: Colors.white,
                fontSize: 22,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 4),
            const Text(
              'Automated safety & optimization checks',
              style: TextStyle(
                color: Colors.white54,
                fontSize: 13,
              ),
            ),
            const SizedBox(height: 24),
            // QC 1: Rules Check - Using actual results
            _buildCheckSection(
              'QC 1: RULES CHECK',
              overallStatus,
              statusColor,
              results.map((result) => _buildCheckItem(
                result.status == CheckStatus.ok,
                result.checkName,
                result.statusText,
              )).toList(),
            ),
            const SizedBox(height: 24),
            // QC 2: AI Analysis
            _buildAISection(),
          ],
        ),
      ),
    );
  }

  Widget _buildCheckSection(String title, String status, Color statusColor, List<Widget> items) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFF232823),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.verified, color: Colors.white54, size: 18),
              const SizedBox(width: 8),
              Text(
                title,
                style: const TextStyle(
                  color: Colors.white70,
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 0.5,
                ),
              ),
              const Spacer(),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: statusColor.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(4),
                ),
                child: Text(
                  status,
                  style: TextStyle(
                    color: statusColor,
                    fontSize: 11,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          ...items,
        ],
      ),
    );
  }

  Widget _buildCheckItem(bool passed, String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        children: [
          Icon(
            passed ? Icons.check_circle : Icons.warning,
            color: passed ? Colors.green : Colors.orange,
            size: 18,
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              label,
              style: const TextStyle(
                color: Colors.white,
                fontSize: 14,
              ),
            ),
          ),
          Text(
            value,
            style: const TextStyle(
              color: Colors.white70,
              fontSize: 13,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAISection() {
    // Note: AI analysis content is placeholder for UI design
    // In production, this would be generated by an AI service using actual client data
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFF232823),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.psychology, color: Color(0xFFa855f7), size: 18),
              const SizedBox(width: 8),
              const Text(
                'QC 2: AI ANALYSIS',
                style: TextStyle(
                  color: Colors.white70,
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 0.5,
                ),
              ),
              const Spacer(),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: const Color(0xFFa855f7).withOpacity(0.2),
                  borderRadius: BorderRadius.circular(4),
                ),
                child: const Text(
                  'GENERATED',
                  style: TextStyle(
                    color: Color(0xFFa855f7),
                    fontSize: 11,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: const Color(0xFF1a1f1a),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  '"The meal plan aligns well with the client\'s PCOS management goals. The distribution of low-glycemic carbs is optimal."',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    height: 1.5,
                  ),
                ),
                const SizedBox(height: 16),
                _buildAIInsight(
                  'Consider adding chia seeds to the Tuesday Oatmeal to boost fiber without spiking insulin.',
                ),
                _buildAIInsight(
                  'Dinner on Wednesday is slightly low on healthy fats for hormone synthesis.',
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAIInsight(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            margin: const EdgeInsets.only(top: 4),
            width: 6,
            height: 6,
            decoration: const BoxDecoration(
              color: Color(0xFFa855f7),
              shape: BoxShape.circle,
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              text,
              style: const TextStyle(
                color: Colors.white70,
                fontSize: 13,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
